version: "3.9"

services:
  database_users:
    image: postgres
    container_name: database_users
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=esferas
      - POSTGRES_DB=esferasDB
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: esferas_app
    ports:
      - 3333:3333
    volumes:
      - .:usr/app
    links:
      - database_users
    depends_on:
      - database_users

volumes:
  pgdata:
    driver: local