version: "3.9"

services:
  database_esferas:
    image: postgres
    container_name: database_esferas
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=esferas
      - POSTGRES_DB=esferasDB
    volumes:
      - pgdata:/data/postgres

  app:
    build: .
    container_name: esferas_app
    ports:
      - 3333:3333
    volumes:
      - .:/usr/app
    links:
      - database_esferas
    depends_on:
      - database_esferas
    environment:
      - DB_HOST=database_esferas

volumes:
  pgdata:
    driver: local